AbbyWeb/Controllers/OrderController.cs
using Abby.DataAccess.Repository.IRepository;
using Microsoft.AspNetCore.Mvc;

namespace AbbyWeb.Controllers
{
	[Route("api/[controller]")]
	[ApiController]
	public class OrderController : Controller
	{
		private readonly IUnitOfWork _unitOfWork;

		public OrderController(IUnitOfWork unitOfWork)
		{
			_unitOfWork = unitOfWork;
		}

		[HttpGet]
		public IActionResult Get(string? status=null)
		{
      Console.WriteLine($"Received status: {status}");
      var orderHeaderList = _unitOfWork.OrderHeader.GetAll(includeProperties: "ApplicationUser");
			if (status != null)
			{
				orderHeaderList = orderHeaderList.Where(u => u.Status.Equals(status, StringComparison.OrdinalIgnoreCase));
			}
			return Json(new { data = orderHeaderList });
		}
	}
}

AbbyWeb/Pages/Admin/Order/ManageOrder.cshtml.cs
using Abby.DataAccess.Repository.IRepository;
using Abby.Models;
using Abby.Models.ViewModel;
using Abby.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AbbyWeb.Pages.Admin.Order
{
  [Authorize(Roles = $"{SD.ManagerRole}, {SD.KitchenRole}")]
  public class ManageOrderModel : PageModel
  {
    private readonly IUnitOfWork _unitOfWork;
    public List<OrderDetailVM> OrderDetailVM { get; set; }
    public ManageOrderModel(IUnitOfWork unitOfWork)
    {
      _unitOfWork = unitOfWork;
    }
    public void OnGet()
    {
      OrderDetailVM = new();
      List<OrderHeader> orderHeaders = _unitOfWork.OrderHeader.GetAll(u => u.Status == SD.StatusSubmitted
      || u.Status == SD.StatusInProcess).ToList();

      foreach(OrderHeader item in orderHeaders)
      {
        OrderDetailVM individual = new OrderDetailVM()
        {
          OrderHeader = item,
          OrderDetails = _unitOfWork.OrderDetails.GetAll(u => u.OrderId == item.Id).ToList()
        };
        OrderDetailVM.Add(individual);
      }
    }

    public IActionResult OnPostHandleStatus(int orderId, string status)
    {
      _unitOfWork.OrderHeader.UpdateStatus(orderId, status);
      _unitOfWork.Save();
      return RedirectToPage("ManageOrder");
    }
  }
}

AbbyWeb/Pages/Admin/Order/OrderDetails.cshtml.cs
using Abby.DataAccess.Repository.IRepository;
using Abby.Models;
using Abby.Models.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Stripe;

namespace AbbyWeb.Pages.Admin.Order
{
  public class OrderDetailsModel : PageModel
  {
    private readonly IUnitOfWork _unitOfWork;
    public OrderDetailVM OrderDetailVM { get; set; }

    public OrderDetailsModel(IUnitOfWork unitOfWork)
    {
      _unitOfWork = unitOfWork;
    }
    public void OnGet(int id)
    {
      OrderDetailVM = new()
      {
        OrderHeader = _unitOfWork.OrderHeader.GetFirstOrDefault(u => u.Id == id, includeProperties: "ApplicationUser"),
        OrderDetails = _unitOfWork.OrderDetails.GetAll(u => u.OrderId == id).ToList()
      };
    }
    public IActionResult OnPostHandleStatus(int orderId, string status)
    {
      if (status == "Refunded")
      {
        OrderHeader orderHeader = _unitOfWork.OrderHeader.GetFirstOrDefault(u => u.Id == orderId);
        var options = new RefundCreateOptions
        {
          Reason = RefundReasons.RequestedByCustomer,
          PaymentIntent = orderHeader.PaymentIntentId,
        };
        var service = new RefundService();
        Refund refund = service.Create(options);
      }

      _unitOfWork.OrderHeader.UpdateStatus(orderId, status);
      _unitOfWork.Save();
      return RedirectToPage("OrderList");
    }
  }
}

AbbyWeb/Pages/Admin/Order/OrderList.cshtml.cs
using Abby.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Net.Http.Headers;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Net.Http;

namespace AbbyWeb.Pages.Admin.Order
{
  [BindProperties]
  public class OrderListModel : PageModel
  {
    private readonly IHttpClientFactory _httpClientFactory;
    public IEnumerable<OrderHeader> resData;
    private readonly ILogger<OrderListModel> _logger;
    public OrderListModel(IHttpClientFactory httpClientFactory, ILogger<OrderListModel> logger)
    {
      _httpClientFactory = httpClientFactory;
      _logger = logger;
    }
    public async Task OnGet(string? status=null)
    {
      try
      {
        var apiUrl = "https://localhost:44301/api/Order";
        var apiUrlStatus = $"{apiUrl}?status={status}";
        var httpRequestMessage = new HttpRequestMessage(
            HttpMethod.Get,
            apiUrlStatus)
        {
          Headers =
            {
                { HeaderNames.Accept, "application/vnd.github.v3+json" },
                { HeaderNames.UserAgent, "HttpRequestsSample" }
            }
        };

        var httpClient = _httpClientFactory.CreateClient();
        var httpResponseMessage = await httpClient.SendAsync(httpRequestMessage);
        _logger.LogInformation("Outer - {0}", httpResponseMessage.IsSuccessStatusCode);

        if (httpResponseMessage.IsSuccessStatusCode)
        {
          var content = await httpResponseMessage.Content.ReadAsStringAsync();
          _logger.LogInformation("Test - {0}", content);
          var obj = JObject.Parse(content);
          _logger.LogInformation("Obj - {0}", obj["data"]);
          var arr = obj["data"];
          resData = arr?.ToObject<IEnumerable<OrderHeader>>(); ;
        }
			} catch(Exception ex)
      {

      }
    }
  }
}

AbbyWeb/Pages/Admin/Order/ManageOrder.cshtml
@page
@model AbbyWeb.Pages.Admin.Order.ManageOrderModel
@using Abby.Utility
@{
}



<h1 class="text-primary py-3">Manage Order's</h1>
<form method="post">
  <div class="container row bg-white p-2 mb-3 rounded">
    @foreach(var item in Model.OrderDetailVM) {
      <div class="col-12 pb-3 pt-3 mt-4 border  rounded">
        <div class="row">
          <div class="col-4">
            Order Number : @item.OrderHeader.Id
            <ul class="text-info">
              @foreach (var details in item.OrderDetails)
              {
                <li>@details.Name x @details.Count</li>
              }
            </ul>
          </div>
          <div class="col-4 pb-2">
            <div class="input-group pb-2">
              <div class="input-group-append">
                <span class="input-group-text bg-secondary border">Time</span>
              </div>
              <input type="text" value="@item.OrderHeader.PickUpTime" class="form-control" readonly />
            </div>
            <textarea asp-for="@item.OrderHeader.Comments" readonly class="rounded border form-control" rows="3"></textarea>
          </div>
          <div class="col-3 offset-1 d-flex align-content-center">
            <div class="col-12">

              @if (item.OrderHeader.Status == SD.StatusSubmitted)
              {
                <button type="submit" class="btn btn-primary form-control mb-3"
                  asp-page-handler="HandleStatus" asp-route-orderId="@item.OrderHeader.Id" asp-route-status="@SD.StatusInProcess">
                  <i class="bi bi-check-square"></i> &nbsp; Start Cooking
                </button>
              }

              @if (item.OrderHeader.Status == SD.StatusInProcess)
              {
                <button type="submit" class="btn btn-success form-control mb-3"
                  asp-page-handler="HandleStatus" asp-route-orderId="@item.OrderHeader.Id" asp-route-status="@SD.StatusReady">
                  <i class="bi bi-emoji-laughing"></i> &nbsp; Order Ready
                </button>
              }

              <button type="submit" class="btn btn-warning form-control mb-3"
                asp-page-handler="HandleStatus" asp-route-orderId="@item.OrderHeader.Id" asp-route-status="@SD.StatusCancelled">
                <i class="bi bi-x-square-fill"></i> &nbsp; Cancel Order
              </button>

            </div>
          </div>
        </div>
      </div>
      }
  </div>

</form>

AbbyWeb/Pages/Admin/Order/OrderDetails.cshtml
@page
@model AbbyWeb.Pages.Admin.Order.OrderDetailsModel
@using Abby.Utility
@{

}
<form method="post">
  <div class="border p-4 ml-1 backgroundWhite mt-4">
    <div class="row pb-1">
      <div class="col-12 col-md-6 ">
        <p class="h2  text-primary">Order Details</p>
      </div>
      <div class="col-12 col-md-4 offset-md-2">
        <a asp-page="/Admin/Order/OrderList" class="btn btn-outline-primary form-control">Back to Orders </a>
      </div>
    </div>
    <hr />

    <div class="row pt-2">

      <div class="col-lg-8 col-12" style="border-right:1px solid #bbb9b9">

        <div class="form-group row py-1">
          <div class="col-md-3 col-12 text-primary">
            Name
          </div>
          <div class="col-md-9 col-12">
            <input asp-for="OrderDetailVM.OrderHeader.PickupName" disabled class="form-control" />
          </div>
        </div>
        <div class="form-group row py-1">
          <div class="col-md-3 col-12 text-primary">
            Email
          </div>
          <div class="col-md-9 col-12">
            <input asp-for="OrderDetailVM.OrderHeader.ApplicationUser.Email" disabled class="form-control" />
          </div>
        </div>
        <div class="form-group row py-1">
          <div class="col-md-3 col-12 text-primary">
            Phone Number
          </div>
          <div class="col-md-9 col-12">
            <input asp-for="OrderDetailVM.OrderHeader.PhoneNumber" disabled class="form-control" />
          </div>
        </div>
        <div class="form-group row py-1">
          <div class="col-md-3 col-12 text-primary">
            Order Total
          </div>
          <div class="col-md-9 col-12">
            <input asp-for="OrderDetailVM.OrderHeader.OrderTotal" disabled class="form-control" />
          </div>
        </div>
        <div class="form-group row py-1">
          <div class="col-md-3 col-12 text-primary">
            Order Date Time
          </div>
          <div class="col-md-9 col-12">
            <input value="@Model.OrderDetailVM.OrderHeader.PickUpTime.ToShortDateString() @Model.OrderDetailVM.OrderHeader.PickUpTime.ToShortTimeString()" disabled class="form-control" />
          </div>
        </div>
        <div class="form-group row py-1">
          <div class="col-md-3 col-12 text-primary">
            Comments
          </div>
          <div class="col-md-9 col-12">
            <textarea asp-for="OrderDetailVM.OrderHeader.Comments" disabled class="form-control" rows="3"></textarea>
          </div>
        </div>

      </div>

      <div class="col-lg-4 col-12">
        <button type="submit" disabled class="btn btn-outline-info form-control">@Model.OrderDetailVM.OrderHeader.Status</button>
        <h4 class="d-flex justify-content-between align-content-center mb-3 pt-3">
          <span class="text-muted">Order ID: </span>
          <span class="badge badge-secondary badge-pill">XXX</span>
        </h4>
        <ul class="list-group mb-3">
          @foreach(var detail in Model.OrderDetailVM.OrderDetails) {
            <li class="list-group-item d-flex justify-content-between">
              <div>
                <h6 class="my-0">@detail.Name</h6>
                <small class="text-muted">Quantity : @detail.Count</small>
              </div>
              <span class="text-muted">$@(detail.Price*detail.Count)</span>
            </li>
          }


          <li class="list-group-item d-flex justify-content-between bg-light">
            <span class="text-info"> Total (USD)</span>
            <strong class="text-info">$@Model.OrderDetailVM.OrderHeader.OrderTotal</strong>
          </li>
        </ul>
        <div class="row pt-3">
          @if (Model.OrderDetailVM.OrderHeader.Status == SD.StatusReady
          && (User.IsInRole(SD.ManagerRole) || User.IsInRole(SD.FrontDeskRole))) {
            <div class="col-12 pb-2">
              <button type="submit" class="btn btn-primary form-control"
                      asp-page-handler="HandleStatus" asp-route-orderId="@Model.OrderDetailVM.OrderHeader.Id" asp-route-status="@SD.StatusCompleted">
                Complete Order
              </button>
            </div>
          }
          @if ((User.IsInRole(SD.ManagerRole) || User.IsInRole(SD.FrontDeskRole))
          && (Model.OrderDetailVM.OrderHeader.Status == SD.StatusReady ||
          Model.OrderDetailVM.OrderHeader.Status == SD.StatusSubmitted ||
          Model.OrderDetailVM.OrderHeader.Status == SD.StatusInProcess)) {
            <div class="col-6">
              <button type="submit" class="btn btn-warning form-control"
                      asp-page-handler="HandleStatus" asp-route-orderId="@Model.OrderDetailVM.OrderHeader.Id" asp-route-status="@SD.StatusCancelled">
                <i class="bi bi-x-square"></i> Cancel Order
              </button>
            </div>
            <div class="col-6">
              <button type="submit" class="btn btn-danger form-control"
                      asp-page-handler="HandleStatus" asp-route-orderId="@Model.OrderDetailVM.OrderHeader.Id" asp-route-status="@SD.StatusRefunded">
                <i class="bi bi-currency-dollar"></i> Refund Order
              </button>
            </div>
          }
        </div>
      </div>
    </div>
  </div>
</form>

AbbyWeb/Pages/Admin/Order/OrderList.cshtml
@page
@using System.Diagnostics
@using Abby.Utility
@model AbbyWeb.Pages.Admin.Order.OrderListModel
@{
}
<div class="container">
  <div class="p-2">
    <ul class="list-group list-group-horizontal-sm">
      <a style="text-decoration: none;" asp-page="OrderList" asp-route-status="@SD.StatusCancelled">
        <li class="list-group-item">Cancelled</li>
      </a>
      <a style="text-decoration: none;" asp-page="OrderList" asp-route-status="@SD.StatusCompleted">
        <li class="list-group-item">Completed</li>
      </a>
      <a style="text-decoration: none;" asp-page="OrderList" asp-route-status="@SD.StatusReady">
      <li class="list-group-item">Ready For PickUp</li>
      </a>
      <a style="text-decoration: none;" asp-page="OrderList" asp-route-status="@SD.StatusInProcess">
      <li class="list-group-item">InProcess</li>
      </a>
    </ul>
  </div>
  <table class="table table-bordered table-striped" style="width:100%">
    <thead>
      <tr class="table-row">
        <th>ORDER ID</th>
        <th>NAME</th>
        <th>EMAIL</th>
        <th>ORDER TOTAL</th>
        <th>PICKUP TIME</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      @if (Model.resData != null)
      {
        @foreach (var item in @Model.resData)
        {
          <tr>
            <td>@item.Id</td>
            <td>@item.ApplicationUser.FirstName @item.ApplicationUser.LastName</td>
            <td>@item.ApplicationUser.Email</td>
            <td>@item.OrderTotal</td>
            <td>@item.PickUpTime</td>
            <td>
              <div class="w-75 btn-group" role="group">
                <a asp-page="OrderDetails" asp-route-id="@item.Id" class="btn btn-primary mx-2">
                  <i class="bi bi-pencil-square"></i>
                </a>
              </div>
            </td>
          </tr>
        }
      }
    </tbody>
  </table>
</div>